# Generated by Django 6.0.6 on 2026-07-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcupapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(default='your last name', max_length=50),
            preserve_default=False,
        ),
    ]
