# Generated by Django 6.0.6 on 2026-07-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcupapp', '0002_student_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='matric_number',
            field=models.CharField(default='', max_length=50),
        ),
    ]
